modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "GNU LGPL 3.0"

[[mods]]
modId = "initialization"
version = "${version}"
logoFile = "assets/initialization/icon.png"
displayName = "Initialization"
displayURL = "https://github.com/ThinkingStudios/initialization"
authors = "TexTrue"
description = '''
Common ModInitializer based on Integration.
'''

[[dependencies.initialization]]
modId = "neoforge"
type = "required"
versionRange = "[21.9,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.initialization]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.9,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.initialization]]
modId = "integration"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"
